// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_log_row_sums
NumericVector cpp_log_row_sums(NumericMatrix m);
RcppExport SEXP _flexmix_cpp_log_row_sums(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_log_row_sums(m));
    return rcpp_result_gen;
END_RCPP
}
// cpp_estep
List cpp_estep(NumericMatrix postunscaled_log, NumericMatrix prior, IntegerVector groupfirst_idx, NumericVector weights);
RcppExport SEXP _flexmix_cpp_estep(SEXP postunscaled_logSEXP, SEXP priorSEXP, SEXP groupfirst_idxSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type postunscaled_log(postunscaled_logSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type groupfirst_idx(groupfirst_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_estep(postunscaled_log, prior, groupfirst_idx, weights));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hard_assign
NumericMatrix cpp_hard_assign(NumericMatrix p, NumericVector weights);
RcppExport SEXP _flexmix_cpp_hard_assign(SEXP pSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hard_assign(p, weights));
    return rcpp_result_gen;
END_RCPP
}
// cpp_group_posteriors
NumericMatrix cpp_group_posteriors(NumericMatrix x, IntegerVector group, int n_groups);
RcppExport SEXP _flexmix_cpp_group_posteriors(SEXP xSEXP, SEXP groupSEXP, SEXP n_groupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_group_posteriors(x, group, n_groups));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flexmix_cpp_log_row_sums", (DL_FUNC) &_flexmix_cpp_log_row_sums, 1},
    {"_flexmix_cpp_estep", (DL_FUNC) &_flexmix_cpp_estep, 4},
    {"_flexmix_cpp_hard_assign", (DL_FUNC) &_flexmix_cpp_hard_assign, 2},
    {"_flexmix_cpp_group_posteriors", (DL_FUNC) &_flexmix_cpp_group_posteriors, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_flexmix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
