# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_log_row_sums <- function(m) {
    .Call(`_flexmix_cpp_log_row_sums`, m)
}

cpp_estep <- function(postunscaled_log, prior, groupfirst_idx, weights) {
    .Call(`_flexmix_cpp_estep`, postunscaled_log, prior, groupfirst_idx, weights)
}

cpp_hard_assign <- function(p, weights) {
    .Call(`_flexmix_cpp_hard_assign`, p, weights)
}

cpp_group_posteriors <- function(x, group, n_groups) {
    .Call(`_flexmix_cpp_group_posteriors`, x, group, n_groups)
}

